# 7-segment display emulation on bitmaps.  3x5 edition with 6:5 aspect ratio.

charset 7seg.cs

aspect-ratio 6:5
circular-dots
baseline 3

# Special case: period drawn outside the 7-segment framework
2E 00 08 00 00

.stroke a 80 80 80 00
.stroke b 00 00 E0 00
.stroke c 00 00 38 00
.stroke d 08 08 08 00
.stroke e 38 00 00 00
.stroke f E0 00 00 00
.stroke g 20 20 20 00

20 00 00 00 00

.include 7seg-compositions.cg
