### !!! Generated by psf2pxf.rb from inputs/consolefonts/default8x9.psf.gz

code 00 = U+2008
code 01 .. 02 = U+263A .. U+263B
code 03 .. 04 = U+2665 .. U+2666
code 05 = U+2663
code 06 = U+2660
code 07 = U+2022
code 08 = U+25D8
code 09 = U+25CB
code 0A = U+25D9
code 0B = U+2642
code 0C = U+2640
code 0D .. 0E = U+266A .. U+266B
code 0E <- U+266C
code 0F = U+263C
code 10 = U+25B6
code 10 <- U+25BA
code 11 = U+25C0
code 11 <- U+25C4
code 12 = U+2195
code 13 = U+203C
code 14 = U+00B6
code 15 = U+00A7
code 16 = U+25AC
code 17 = U+21A8
code 18 = U+2191
code 19 = U+2193
code 1A = U+2192
code 1B = U+2190
code 1C = U+221F
code 1C <- U+2319
code 1D = U+2194
code 1E = U+25B2
code 1F = U+25BC
include ascii.cs
code 7F = U+2302
code 80 = U+00C7
code 81 = U+00FC
code 82 = U+00E9
code 83 = U+00E2
code 84 = U+00E4
code 85 = U+00E0
code 86 = U+00E5
code 87 = U+00E7
code 88 .. 89 = U+00EA .. U+00EB
code 8A = U+00E8
code 8B = U+00EF
code 8C = U+00EE
code 8D = U+00EC
code 8E .. 8F = U+00C4 .. U+00C5
code 8F <- U+212B
code 90 = U+00C9
code 91 = U+00E6
code 92 = U+00C6
code 93 = U+00F4
code 94 = U+00F6
code 95 = U+00F2
code 96 = U+00FB
code 97 = U+00F9
code 98 = U+00FF
code 99 = U+00D6
code 9A = U+00DC
code 9B .. 9C = U+00A2 .. U+00A3
code 9D = U+00A5
code 9E = U+20A7
code 9F = U+0192
code A0 = U+00E1
code A1 = U+00ED
code A2 = U+00F3
code A3 = U+00FA
code A4 = U+00F1
code A5 = U+00D1
code A6 = U+00AA
code A7 = U+00BA
code A8 = U+00BF
code A9 = U+2310
code AA = U+00AC
code AB = U+00BD
code AC = U+00BC
code AD = U+00A1
code AE = U+00AB
code AF = U+00BB
code B0 .. B2 = U+2591 .. U+2593
code B3 = U+2502
code B4 = U+2524
code B5 .. B6 = U+2561 .. U+2562
code B7 = U+2556
code B8 = U+2555
code B9 = U+2563
code BA = U+2551
code BB = U+2557
code BC = U+255D
code BD = U+255C
code BE = U+255B
code BF = U+2510
code C0 = U+2514
code C1 = U+2534
code C2 = U+252C
code C3 = U+251C
code C4 = U+2500
code C5 = U+253C
code C6 .. C7 = U+255E .. U+255F
code C8 = U+255A
code C9 = U+2554
code CA = U+2569
code CB = U+2566
code CC = U+2560
code CD = U+2550
code CE = U+256C
code CF .. D0 = U+2567 .. U+2568
code D1 .. D2 = U+2564 .. U+2565
code D3 = U+2559
code D4 = U+2558
code D5 .. D6 = U+2552 .. U+2553
code D7 = U+256B
code D8 = U+256A
code D9 = U+2518
code DA = U+250C
code DB = U+2588
code DC = U+2584
code DD = U+258C
code DE = U+2590
code DF = U+2580
code E0 = U+03B1
code E1 = U+00DF
code E1 <- U+03B2
code E2 = U+0393
code E3 = U+03C0
code E4 = U+03A3
code E5 = U+03C3
code E6 = U+00B5
code E6 <- U+03BC
code E7 = U+03C4
code E8 = U+03A6
code E9 = U+0398
code EA = U+03A9
code EA <- U+2126
code EB = U+03B4
code EC = U+221E
code ED = U+03C6
code ED <- U+2205
code ED <- U+2300
code EE = U+03B5
code EE <- U+2208
code EF = U+2229
code F0 = U+2261
code F1 = U+00B1
code F2 = U+2265
code F3 = U+2264
code F4 .. F5 = U+2320 .. U+2321
code F6 = U+00F7
code F7 = U+2248
code F8 = U+00B0
code F9 = U+2219
code F9 <- U+22C5
code FA = U+00B7
code FB = U+221A
code FC = U+207F
code FD = U+00B2
code FE = U+220E
code FE <- U+25A0
code FF = U+00A0
