#! /bin/sh

(
  echo "### !!! Generated by overviews/charset.dep.sh"
  echo
  echo "# This file contains make(1) rules to let the stable overviews depend"
  echo "# on their corresponding fonts' charset files."
  echo
  ./pixitie --list-font-charsets | sed -e 's,^,overviews/,; s,:,.ps:,'
) > overviews/charset.dep
