### !!! Generated by psf2pxf.rb from inputs/consolefonts/GohaClassic-12.psf.gz

code 00 = U+FFFD
code 01 .. 02 = U+263A .. U+263B
code 03 .. 04 = U+2665 .. U+2666
code 05 = U+2663
code 06 = U+2660
code 07 = U+2022
code 08 = U+25D8
code 09 = U+25CB
code 0A = U+25D9
code 0B = U+2642
code 0C = U+2640
code 0D .. 0E = U+266A .. U+266B
code 0E <- U+266C
code 0F = U+263C
code 10 = U+25B6
code 10 <- U+25BA
code 11 = U+25C0
code 11 <- U+25C4
code 12 = U+2195
code 13 = U+203C
code 14 = U+00B6
code 15 = U+00A7
code 16 = U+25AC
code 17 = U+21A8
code 18 = U+2191
code 19 = U+2193
code 1A = U+2192
code 1B = U+2190
code 1C = U+221F
code 1C <- U+2319
code 1D = U+2194
code 1E = U+25B2
code 1F = U+25BC
include ascii.cs
code 7F = U+2302
code 9F .. A5 = U+1200 .. U+1206
code A6 .. E4 = U+1208 .. U+1246
code E5 = U+1248
code E6 .. E9 = U+124A .. U+124D
code EA .. F0 = U+1250 .. U+1256
code F1 = U+1258
code F2 .. F5 = U+125A .. U+125D
code F6 .. 11C = U+1260 .. U+1286
code 11D = U+1288
code 11E .. 121 = U+128A .. U+128D
code 122 .. 140 = U+1290 .. U+12AE
code 141 = U+12B0
code 142 .. 145 = U+12B2 .. U+12B5
code 146 .. 14C = U+12B8 .. U+12BE
code 14D = U+12C0
code 14E .. 151 = U+12C2 .. U+12C5
code 152 .. 158 = U+12C8 .. U+12CE
code 159 .. 15F = U+12D0 .. U+12D6
code 160 .. 196 = U+12D8 .. U+130E
code 197 = U+1310
code 198 .. 19B = U+1312 .. U+1315
code 19C .. 1A2 = U+1318 .. U+131E
code 1A3 .. 1C9 = U+1320 .. U+1346
code 1CA .. 1DC = U+1348 .. U+135A
code 1DD .. 1F9 = U+1360 .. U+137C
code 1FA = U+FDF0
code 1FB .. 1FF = U+FDFB .. U+FDFF
