### !!! Generated by psf2pxf.rb from inputs/consolefonts/lat1-08.psf.gz

code 00 = U+FFFD
code 01 = U+2248
code 02 .. 03 = U+0152 .. U+0153
code 04 = U+25C6
code 05 = U+2409
code 06 .. 07 = U+240C .. U+240D
code 08 = U+240A
code 09 .. 0B = U+2591 .. U+2593
code 0C = U+2588
code 0D = U+2584
code 0E = U+2580
code 0F = U+258C
code 10 = U+2590
code 11 = U+2424
code 12 = U+240B
code 13 .. 14 = U+2264 .. U+2265
code 15 = U+2260
code 16 = U+25C0
code 17 = U+25B6
code 18 = U+2191
code 19 = U+2193
code 1A = U+2192
code 1B = U+2190
code 1C = U+2195
code 1D = U+2194
code 1E = U+21B5
code 1F = U+03C0
code 20 .. 7E = U+0020 .. U+007E
code 20 <- U+00A0
code 4B <- U+212A
code 5F <- U+F804
code 7F = U+0178
code 80 .. 9F = U+00C0 .. U+00DF
code 85 <- U+212B
code A0 = U+2423
code A1 .. BF = U+00A1 .. U+00BF
code AF <- U+F800
code C0 = U+F801
code C1 .. C2 = U+2575 .. U+2576
code C3 = U+2514
code C4 = U+2577
code C5 = U+2502
code C6 = U+250C
code C7 = U+251C
code C8 = U+2574
code C9 = U+2518
code CA = U+2500
code CB = U+2534
code CC = U+2510
code CD = U+2524
code CE = U+252C
code CF = U+253C
code D0 = U+F803
code D1 .. D2 = U+2579 .. U+257A
code D3 = U+2517
code D3 <- U+255A
code D4 = U+257B
code D5 = U+2503
code D5 <- U+2551
code D6 = U+250F
code D6 <- U+2554
code D7 = U+2523
code D7 <- U+2560
code D8 = U+2578
code D9 = U+251B
code D9 <- U+255D
code DA = U+2501
code DA <- U+2550
code DB = U+253B
code DB <- U+2569
code DC = U+2513
code DC <- U+2557
code DD = U+2563
code DD <- U+252B
code DE = U+2533
code DE <- U+2566
code DF = U+254B
code DF <- U+256C
code E0 .. FF = U+00E0 .. U+00FF
